language: java
jdk:
  - openjdk11
notifications:
  email:
    recipients:
      - eclaros@fi.uba.ar
      - gabrielamendezg@outlook.com
    on_failure: always
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
